### ISSUE TITLE
导入后按键里面会多出许多enc，导致无法使用

### ISSUE THREAD

**Issue by jqrxjkpyjpn** [cgcel/rime_to_gboard#1]
比如“万词王”会变成“ enc dudi”
![photo_2023-08-19_17-19-47](https://github.com/cgcel/rime_to_gboard/assets/47104294/a6f2ca79-2a4f-4316-af9b-3d54883081b2)

**Comment by velviagris** [comment]
这个脚本只测试过全拼方案，截图里的是什么输入方案？

**Comment by velviagris** [comment]
如果是五笔的话能不能贴一部分 userdb.txt 的内容给我参考一下

**Comment by jqrxjkpyjpn** [comment]
> 如果是五笔的话能不能贴一部分 userdb.txt 的内容给我参考一下

![Snipaste_2023-08-20_07-25-18](https://github.com/cgcel/rime_to_gboard/assets/47104294/d25314c3-56fa-4456-a057-ca90787ea483)
感谢作者，没想到会回复这么快！！

**Comment by jqrxjkpyjpn** [comment]
我使用的是五笔86版

**Comment by velviagris** [comment]
尝试修复了, 请试一下 v0.0.2 release

**Comment by jqrxjkpyjpn** [comment]
> 尝试修复了, 请试一下 v0.0.2 release

导入成功了，但是部分词组打不出来……
比方说，rrrr在字典里是乒乒乓乓，但是候选里面并没有这个词组。
![image](https://github.com/cgcel/rime_to_gboard/assets/47104294/4390cce4-ef15-427b-b66c-652e81a8231d)
![image](https://github.com/cgcel/rime_to_gboard/assets/47104294/aa460bc4-acb1-4c9e-a366-f62215ba4a02)

经反复尝试，部分词组会被程序判定为拼音。如“rrrr=乒乒乓乓”这个词组，只有在拼音模式下才会跳出来。
而且在只安装五笔输入法的情况下导入，结果依旧。
目前不确定是程序自动划分归类的，还是说导入字典时，里面会有什么标记之类的，会标记这个词组是属于哪种输入法。（我不懂编程啊，瞎猜的。）

另，在研究词组的时候发现，先前的问题里，这个enc在txt里打开是这样的
![image](https://github.com/cgcel/rime_to_gboard/assets/47104294/7fc25f34-7976-4ba9-b653-6957044b02a0)

又翻了一下这个rime输入法的相关资料，初步估计应该是一种标记，标记这个词组用户输入过，但输入次数没达到设定值，算是未进入正式词组的预备词组，因为基本都是不成文的词频是0的。

**Comment by velviagris** [comment]
你可以尝试直接在gboard里加词库（这些词要能打出来）然后在gboard导出.zip文件，看看里面的格式是怎么样的吗，因为我不用五笔所以不太清楚是怎么样的格式😂

**Comment by jqrxjkpyjpn** [comment]
尝试了好久，确认了，它这个造词只能在拼音里打出来……心好累。
准备给他们开发组发邮件反馈了。

**Comment by velviagris** [comment]
那就没办法了😂😂那这个issue我先关闭
